backendUrl = "some url"
frontendUrl = "some url"
mobileUrl = "some url"
dataFolder = "folder here"
categoryBaseUrl = ""
technologyBaseUrl = ""
fulltextBaseUrl = ""
headerHost = ""
headerReferer = ""
headerOrigin = ""
dbPath = ""
