backendUrl = "some url"
frontendUrl = "some url"
mobileUrl = "some url"
dataFolder = "folder here"
oldDataFolder = "old folder here"
categoryBaseUrl = ""
technologyBaseUrl = ""
headerHost = ""
headerReferer = ""
headerOrigin = ""
